# yaml-language-server: https://json.schemastore.org/github-workflow.json

# Continuous Delivery Example (requires manual intervention to deploy to each environment)
# Use environments to require manual approvals between jobs
# Environments require public repositories or private repositories on GitHub with Enterprise plans

name: Continuous Delivery

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  # Build Application
  Build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Build Steps Here
        run: echo "Secret - ${{ secrets.Message }}"

  # Deploy to the Development servers
  DeployDev:
    name: Development
    if: github.event_name == 'pull_request'
    needs: Build
    runs-on: ubuntu-latest
    environment: DEV
    
    steps:
      - name: Deploy to DEV
        run: echo "Deploy Application to DEV"

  # Deploy to the UAT servers
  DeployUat:
    name: UAT
    if: github.event.ref == 'refs/heads/main'
    needs: Build
    runs-on: ubuntu-latest
    environment: 
      name: UAT
      url: https://uat.application.com
    
    steps:
      - name: Deploy to UAT
        run: echo "Deploy Application to UAT"

  # Deploy to the Staging servers
  DeployStage:
    name: Stage
    needs: DeployUat
    runs-on: ubuntu-latest
    environment: 
      name: STAGE
      url: https://stage.application.com
    
    steps:
      - name: Deploy to Stage
        run: echo "Deploy Application to Stage"

  # Deploy to the Production servers
  DeployProduction:
    name: Production
    needs: DeployStage
    runs-on: ubuntu-latest
    environment: 
      name: PROD
      url: https://application.com

    steps:
      - name: Deploy to Production
        run: echo "Deploy Application to Production"
