# yaml-language-server: https://json.schemastore.org/github-workflow.json
name: Continuous Integration

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Secret Message
        run: echo "Secret - ${{ secrets.Message }}"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Deploy Application"
      
